name: Sync Fork to satwareAG

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0
          
      - name: Checkout destination fork
        uses: actions/checkout@v3
        with:
          repository: satwareAG/skoolesi
          path: destination
          token: ${{ secrets.SYNC_PAT }}
          fetch-depth: 0
          
      - name: Sync changes
        run: |
          cd destination
          git remote add upstream https://github.com/jane-alesi/skoolesi.git
          git fetch upstream
          git checkout main
          git merge upstream/main --allow-unrelated-histories -X theirs
          git push origin main
