name: Sync Fork to satwareAG

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
          repository: satwareAG/skoolesi
          
      - name: Sync fork
        uses: tgymnich/fork-sync@v1.4.5
        with:
          token: ${{ steps.generate_token.outputs.token }}
          owner: satwareAG
          base: main
          head: main
          merge_method: merge
